global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'stock4u_api'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['localhost:8000']
    scrape_timeout: 10s
    # Use a bearer token from a file to authenticate to the API
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/token.txt


